dist: trusty
language: node_js
node_js:
  - node

cache: npm

before_install:
  - git config --global user.email "Ansible_TravisCI@f5.com"
  - git config --global user.name "Travis F5 Ansible"

install:
  npm install

jobs:
  include:
    - name: Screenshot John Hopkins Covid-19 ArcGIS page
      script:
        - node index.js -u 'https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6'
    - name: Screenshot John Hopkins Covid-19 ArcGIS world map
      script:
        -  node index.js -u 'https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6' -e 'div#ember61'
    - name: Screenshot eleval observablehq div
      script:
        -  node index.js -u 'https://observablehq.com/@elaval/coronavirus-worldwide-evolution' -e 'div#el2'
    - name: Screenshot eleval observablehq page
      script:
        -  node index.js -u 'https://observablehq.com/@elaval/coronavirus-worldwide-evolution'
    - name: Screenshot worldspandemic World card
      script:
        -  node index.js -u 'https://worldspandemic.com/'  -e '.cov19u-card'
    - name: Screenshot worldspandemic Total World chart
      script:
        -  node index.js -u 'https://worldspandemic.com/'  -e '.covid19-ultimate-evolution-chart'
    - name: Screenshot worldspandemic Daily New Cases World chart
      script:
        -  node index.js -u 'https://worldspandemic.com/'  -e '.covid19-ultimate-daily-chart'
    
deploy:
  provider: releases
  api_key: ${RELEASE_KEY}
  file_glob: true
  file: screenshots/screenshot_*
  skip_cleanup: true
