dist: trusty
language: node_js
node_js:
  - node

cache: npm

before_install:
  - git config --global user.email "Ansible_TravisCI@f5.com"
  - git config --global user.name "Travis F5 Ansible"

install:
  npm install

jobs:
  include:
    - name: Run all screenshots
      script:
        - bash runner.sh
    
deploy:
  provider: releases
  api_key: ${RELEASE_KEY}
  file_glob: true
  # file: screenshots/screenshot_*
  file: screenshots.zip
  skip_cleanup: true
