dist: trusty
language: node_js
node_js:
  - node

cache: npm

before_install:
  - git config --global user.email "nitinthewiz@gmail.com"
  - git config --global user.name "Nitin Khanna"

install:
  npm install

branches:
  only:
  - master

jobs:
  include:
    - stage: GitHub Release
      script:
        - echo "Run all screenshots"
        - node runner.js
        - echo "Deploying to GitHub releases"
      before_deploy:
         - if ! [[ $TRAVIS_TAG ]]; then
           export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)} &&
           git tag $TRAVIS_TAG;
           fi
      deploy:
        - provider: releases
          api_key: ${RELEASE_KEY}
          file_glob: true
          file: /tmp/screenshots.zip
          cleanup: false
        - provider: s3
          access_key_id: ${AWS_ACCESS_KEY}
          secret_access_key: ${AWS_SECRET_KEY}
          bucket: ${AWS_S3_BUCKET}
          cleanup: false
          region: ${AWS_REGION}
          glob: "**/*"
          local_dir: screenshots
          upload_dir: screenshots
      after_deploy:
        - node post_deploy.js
